import { Inter } from 'next/font/google'
import './globals.css'
import UIProvider from './UIProvider'
import AuthProvider from './AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <UIProvider>{children}</UIProvider>
        </body>
      </html>
    </AuthProvider>
  )
}
